server:
  port: 7090
  servlet:
    context-path: /estempalte
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 192.168.22.165:9301
  kafka:
    consumer:
      group-id: 1
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
      bootstrap-servers: 192.168.22.165:9092,192.168.22.166:9092,192.168.22.167:9092
      session-timeout: 30000
    producer:
      bootstrap-servers: 192.168.22.165:9092,192.168.22.166:9092,192.168.22.167:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      batch-size: 16384
      lingerMs: 1
      buffer-memory: 33554432